### ISSUE TITLE
Query into Dgraph from client side blocked by CORS policy

### ISSUE THREAD

**Issue by monatis** [dgraph-io/graphoverflow#11]
Hi, I'm testing Graphoverflow on Windows, and I managed to install it, load data, make it launch, log in by Github, create a question by going to `/questions/ask`, etc., everything seems to be working as expected. But it cannot reach dgraph http api from the client side because it is blocked by CORS policy. I found the following message in my console log (Google Chrome): 
```fetch at 'http://localhost:8080/query/0' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field x-dgraph-linread is not allowed by Access-Control-Allow-Headers in preflight response.```

Additionally, why are we making dgraph directly accessible from the client --isn't it a security risk? Is it only for demonstrational purposes, or am I missing something?

**Comment by MichelDiz** [comment]
Can you test this PR? https://github.com/dgraph-io/graphoverflow/pull/12

Cheers.
