### ISSUE TITLE
UNMET PEER DEPENDENCY react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0

### ISSUE THREAD

**Issue by lonnieOST** [dgraph-io/graphoverflow#8]
Hello,

Seems that there is a problem compiling with "npm install"   using node v5 and v6

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN optional Skipping failed optional dependency /nodemon/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.4
npm WARN react-redux@5.0.7 requires a peer of react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0 but none was installed.
npm WARN server@1.0.0 No description
npm

I am compiling on Ubuntu 16.04 (x64)

Can you please look into this?
Thanks

**Comment by lonnieOST** [comment]
Would it be possible for you to please step through your setup and run steps for this project as I cannot seem to get it work properly and I think that something is missing.

Cheers,

**Comment by lonnieOST** [comment]
I now have the UI coming up but no connection to Dgraph

**Comment by MichelDiz** [comment]
Graphoverflow is now working fine. Thanks for reporting this.
